# 作业
---
1. 创建四个一维数组(向量)，长度均为100，分别服从正态分布
2. 将四个数组分别进行平方、开方、指数、余弦运算
3. 将四个数组合并为100* 4的矩阵结构，其中第一列代表一个原数组
4. 分别计算该矩阵与其转置的乘积(AA)，及其转置与原矩阵的乘积(ATA)，并计算其特征值和特征向量
5. 生成该矩阵的第5列，为该矩阵前四列的加权和，权重向量为[1,2,3,4]
6. 将第五列归一化至[0，1]区间

In [1]:
import numpy as np

## q1
---
**利用np.random.normal随机生成正态分布函数**

In [2]:
np.random.seed(0)
vector1 = np.random.normal(loc=0, scale=1, size=100)
vector2 = np.random.normal(loc=0, scale=1, size=100)
vector3 = np.random.normal(loc=0, scale=1, size=100)
vector4 = np.random.normal(loc=0, scale=1, size=100)

## q2
---
**利用np进行运算，其中开方运算取绝对值后进行开方**

In [3]:
square_res = []
square_res.append(np.square(vector1))
square_res.append(np.square(vector2))
square_res.append(np.square(vector3))
square_res.append(np.square(vector4))

sqrt_res = []
sqrt_res.append(np.sqrt(abs(vector1)))
sqrt_res.append(np.sqrt(abs(vector2)))
sqrt_res.append(np.sqrt(abs(vector3)))
sqrt_res.append(np.sqrt(abs(vector4)))

exp_res = []
exp_res.append(np.exp(vector1))
exp_res.append(np.exp(vector2))
exp_res.append(np.exp(vector3))
exp_res.append(np.exp(vector4))

cos_res = []
cos_res.append(np.cos(vector1))
cos_res.append(np.cos(vector2))
cos_res.append(np.cos(vector3))
cos_res.append(np.cos(vector4))

## q3
---
**利用np.column_stack进行矩阵拼接**

In [4]:
matrix = np.column_stack((vector1, vector2, vector3, vector4))
np.round(matrix, 2)

array([[ 1.76,  1.88, -0.37, -1.31],
       [ 0.4 , -1.35, -0.24,  1.66],
       [ 0.98, -1.27,  1.1 , -0.12],
       [ 2.24,  0.97,  0.66, -0.68],
       [ 1.87, -1.17,  0.64,  0.67],
       [-0.98,  1.94, -1.62, -0.46],
       [ 0.95, -0.41, -0.02, -1.33],
       [-0.15, -0.75, -0.74, -1.35],
       [-0.1 ,  1.92,  0.28,  0.69],
       [ 0.41,  1.48, -0.1 , -0.16],
       [ 0.14,  1.87,  0.91, -0.13],
       [ 1.45,  0.91,  0.32,  1.08],
       [ 0.76, -0.86,  0.79, -1.13],
       [ 0.12,  1.91, -0.47, -0.73],
       [ 0.44, -0.27, -0.94, -0.38],
       [ 0.33,  0.8 , -0.41,  0.09],
       [ 1.49,  0.95, -0.02, -0.04],
       [-0.21, -0.16,  0.38, -0.29],
       [ 0.31,  0.61,  2.26, -0.06],
       [-0.85,  0.92, -0.04, -0.11],
       [-2.55,  0.38, -0.96, -0.72],
       [ 0.65, -1.1 , -0.35, -0.81],
       [ 0.86,  0.3 , -0.46,  0.27],
       [-0.74,  1.33,  0.48, -0.89],
       [ 2.27, -0.69, -1.54, -1.16],
       [-1.45, -0.15,  0.06, -0.31],
       [ 0.05, -0.44,  0.16, -0.16],
 

## q4
---
**计算AAT和ATA并求特征值和特征向量**

In [5]:
AAT = np.dot(matrix, matrix.T)
ATA = np.dot(matrix.T, matrix)
eigvals_AAT, eigvecs_AAT = np.linalg.eig(AAT)
eigvals_ATA, eigvecs_ATA = np.linalg.eig(ATA)
print(f'AAT: \n{np.round(AAT,0)} \n ATA: \n{np.round(ATA,0)}')

AAT: 
[[ 9. -4. -1. ...  3.  3.  2.]
 [-4.  5.  2. ...  1. -0. -0.]
 [-1.  2.  4. ...  1. -3. -1.]
 ...
 [ 3.  1.  1. ...  6.  3.  3.]
 [ 3. -0. -3. ...  3.  7.  4.]
 [ 2. -0. -1. ...  3.  4.  3.]] 
 ATA: 
[[102.  12.   7.  -7.]
 [ 12. 108.   5.   6.]
 [  7.   5.  91.  12.]
 [ -7.   6.  12.  90.]]


## q5
---
**加权求和**

In [6]:
weights = np.array([1, 2, 3, 4])
col5 = np.dot(matrix, weights)
matrix_res = np.column_stack([matrix, col5])
np.round(matrix_res[:5], 2)

array([[ 1.76,  1.88, -0.37, -1.31, -0.8 ],
       [ 0.4 , -1.35, -0.24,  1.66,  3.62],
       [ 0.98, -1.27,  1.1 , -0.12,  1.26],
       [ 2.24,  0.97,  0.66, -0.68,  3.42],
       [ 1.87, -1.17,  0.64,  0.67,  4.11]])

## q6
---
**归一化**

In [7]:
col5_normalized = (col5 - np.min(col5)) / (np.max(col5) - np.min(col5))
matrix_res_normalized = np.column_stack([matrix[:, :4], col5_normalized])
np.round(matrix_res_normalized[:5], 2)

array([[ 1.76,  1.88, -0.37, -1.31,  0.52],
       [ 0.4 , -1.35, -0.24,  1.66,  0.67],
       [ 0.98, -1.27,  1.1 , -0.12,  0.59],
       [ 2.24,  0.97,  0.66, -0.68,  0.66],
       [ 1.87, -1.17,  0.64,  0.67,  0.68]])